# Generated by Django 5.0.3 on 2024-03-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_group', models.CharField()),
                ('unit_of_measurement', models.CharField()),
                ('quantity', models.IntegerField()),
                ('price_without_vat', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('storage_location', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TmaRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField()),
                ('unit_of_measurement', models.CharField()),
                ('quantity', models.IntegerField()),
                ('price_without_vat', models.IntegerField()),
                ('comment', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tma_app.items')),
            ],
        ),
    ]
