# Generated by Django 5.0.3 on 2024-03-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_app', '0003_alter_items_item_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Kilogram', 'Kilogram'), ('Miligram', 'Miligram')], default='Kilogram'),
        ),
    ]
