# Generated by Django 5.0.3 on 2024-03-19 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_app', '0005_alter_tmarequests_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmarequests',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tma_app.items'),
        ),
    ]
