# Generated by Django 5.0.3 on 2024-03-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_app', '0006_alter_tmarequests_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmarequests',
            name='status',
            field=models.CharField(choices=[('Denied', 'Denied'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', null=True),
        ),
    ]
