# Generated by Django 5.0.3 on 2024-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_app', '0007_alter_tmarequests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmarequests',
            name='status',
            field=models.CharField(choices=[('Denied', 'Denied'), ('Approved', 'Approved'), ('New', 'New')], default='New', null=True),
        ),
    ]
